//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBMCLAPI_IN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenBMCLAPI_IN.Resources.LogResource", typeof(LogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully got config file:\n\n{0}\n.
        /// </summary>
        public static string debug_got_config_file {
            get {
                return ResourceManager.GetString("debug.got_config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger initialized with properties:\n\npath: {0},\nrollOnFileSizeLimit: {1},\nfileSizeLimit: {2} bytes,\nrollingInterval: {3},\noutputTemplate: {4},\nretainedFileCountLimit: {5}\n.
        /// </summary>
        public static string debug_logger_initialized {
            get {
                return ResourceManager.GetString("debug.logger_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reach measure file {0}. Get status code {1} with information: \n{2}.
        /// </summary>
        public static string error_failed_to_reach_measure {
            get {
                return ResourceManager.GetString("error.failed_to_reach_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file to your storage, for more information, please see the log below. File path: {0}.
        /// </summary>
        public static string error_failed_to_upload_file {
            get {
                return ResourceManager.GetString("error.failed_to_upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify the measure file because some fatal error occured in the process. See logs below for more information.
        /// </summary>
        public static string error_failed_to_verify_measure {
            get {
                return ResourceManager.GetString("error.failed_to_verify_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure files have been created successfully.
        /// </summary>
        public static string info_created_measure {
            get {
                return ResourceManager.GetString("info.created_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully got config file.
        /// </summary>
        public static string info_got_config_file {
            get {
                return ResourceManager.GetString("info.got_config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger initialization finished.
        /// </summary>
        public static string info_logger_initialized {
            get {
                return ResourceManager.GetString("info.logger_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification for measure file {0} passed.
        /// </summary>
        public static string info_measure_verification_passed {
            get {
                return ResourceManager.GetString("info.measure_verification_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded file : {0}.
        /// </summary>
        public static string info_upload_success {
            get {
                return ResourceManager.GetString("info.upload_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find measure file: {0}, ready to create it.
        /// </summary>
        public static string warning_measure_not_found {
            get {
                return ResourceManager.GetString("warning.measure_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of measure file {0} mismatched(Current: {1}, Expected: {2}). Ready to recreate it.
        /// </summary>
        public static string warning_measure_size_not_match {
            get {
                return ResourceManager.GetString("warning.measure_size_not_match", resourceCulture);
            }
        }
    }
}
